# Generated by Django 2.2.2 on 2019-07-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('blog_date', models.DateTimeField(verbose_name='date published')),
                ('blog_url', models.CharField(max_length=200)),
                ('word_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('header_one', models.CharField(max_length=200)),
                ('header_two', models.CharField(max_length=200)),
                ('header_three', models.CharField(max_length=200)),
                ('external_link', models.CharField(max_length=200)),
                ('internal_link', models.CharField(max_length=200)),
                ('readability_score', models.IntegerField(default=0)),
                ('company_name', models.IntegerField(default=0)),
            ],
        ),
    ]
